export type RootStackParamList = {
  Onboarding: undefined;
  Login: undefined;
  RegisterRole: undefined;
  RegisterInfo: { role: string };
  Loading: undefined;
  Home: undefined;
  NoTeam: undefined;
  CreateTeam: undefined;
  Act5Start: undefined;
  Act5Authentication: undefined;
  Act5Equipment: undefined;
  Act5Instruction: undefined;
  Act5Experiment: { docIds?: string[] } | undefined;
  Act5RecordingResult: { docIds: string[] };
  Act5ResultComp: { docIds: string[] };
  Act5Reflection1: { docIds: string[] };
  Act5Reflection2: { docIds: string[] };
  Act5Reflection3: { docIds: string[] };
  Act5Discussion: { docIds: string[] };
  Act5Curriculum: undefined;
  RateActivity: undefined;
  Act6RateActivity: undefined;
  Act7RateActivity: undefined;
  TeamPageChem: undefined;
  Leaderboard: undefined;
  Profile: undefined;
  Act6Start: undefined;
  Act6Authentication: undefined;
  Act6Equipment: undefined;
  Act6Instruction: undefined;
  Act6Instruction2: undefined;
  Act6Phase1Start: undefined;
  Act6Phase2Start: undefined;
  Act6Phase3Start: undefined;
  Act6Experiment1: undefined;
  Act6Experiment2: undefined;
  Act6Experiment3: undefined;
  Act6Phase1Result: undefined;
  Act6Phase2Result: undefined;
  Act6Phase3Result: undefined;
  Act6Phase1And2Result: undefined;
  Act6Reflection: { docIds: string[] };
  Act6Discussion: { docIds: string[] };
  Act6Curriculum: undefined;
  Act7Start: undefined;
  Act7Authentication: undefined;
  Act7Equipment: undefined;
  Act7Instruction: undefined;
  Act7Reflection: { docIds: string[] };
  Act7Discussion: { docIds: string[] };
  Act7Curriculum: undefined;
  Act7Experiment1: undefined;
  Act7Result1: { docIds: string[] };
  Act7Result2: { docIds: string[] };
  Act7Result3: { docIds: string[] };
  Act7Experiment2: { docIds?: string[] } | undefined;
  Act7Experiment3: { docIds?: string[] } | undefined;
};


